---
  - name: Install Docker
    ansible.builtin.package:
      name:
        - docker
        - docker.io
        - docker-compose
      state: present 

  - name: Start freshrss
    community.docker.docker_compose:
      project_src: "{{ FRESHRSS_PATH }}/docs"
      files: "docker-compose.yml"

