---
  - name: Create folders
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
    loop:
      - "{{ FRESHRSS_PATH }}"
      - "{{ FRESHRSS_PATH }}/volumes"
      - "{{ FRESHRSS_PATH }}/volumes/config"
      - "{{ FRESHRSS_PATH }}/backups"
      - "{{ FRESHRSS_PATH }}/backups/database"
      - "{{ FRESHRSS_PATH }}/backups/tarballs"
      - "{{ FRESHRSS_PATH }}/backups/logs"
      - "{{ FRESHRSS_PATH }}/scripts"
      - "{{ FRESHRSS_PATH }}/docs"


  - name: Copy docker compose file
    ansible.builtin.template:
      src: "{{ role_path }}/templates/freshrss_docker-compose.yml.j2"
      dest: "{{ FRESHRSS_PATH }}/docs/docker-compose.yml"

  - name: Install nginx
    ansible.builtin.package:
      name: nginx
      state: 'latest'

  - name: Install sqlite3
    ansible.builtin.package:
      name: sqlite3

  - name: Copy dump database scripts
    ansible.builtin.template:
      src: "{{ role_path }}/templates/backup_freshrss.sh.j2"
      dest: "{{ FRESHRSS_PATH }}/scripts/backup_freshrss.sh"
      mode: "0700"

  - name: Create cronjob to run database dump script daily at 10pm
    ansible.builtin.cron:
      backup: true
      hour: 22
      minute: 0
      job: "bash {{ FRESHRSS_PATH }}/scripts/backup_freshrss.sh -n 30"
      name: "Freshrss - Dump Databases"
      state: "present"
      
# TODO If selinux, flip selinux booleans

