---
  - name: Check if docker-compose file exists
    ansible.builtin.stat:
      path: "{{ FRESHRSS_PATH }}/docs/docker-compose.yml"
    register: freshrss_stat_docker_compose_file

  - name: Docker Compose Stop Running Apps
    community.docker.docker_compose:
      project_src: "{{ FRESHRSS_PATH }}/docs"
      files: "docker-compose.yml"
      state: absent
    when: freshrss_stat_docker_compose_file.stat.exists

  - name: Remove cronjobs
    ansible.builtin.cron:
      backup: true
      hour: 22
      minute: 0
      job: "bash {{ FRESHRSS_PATH }}/scripts/backup_freshrss.sh -n 30"
      name: "Freshrss - Dump Databases"
      state: "absent"